### ISSUE TITLE
Add floating Pokémon

### ISSUE THREAD

**Issue by varkor** [varkor/pokengine#146]
Pokémon that fly or levitate will need to be identified for Sky Battles anyway, so some sort of property is needed for this. It'd make sense to make it even more general purpose, and allow Pokémon to be classed as "swimming" or other such things, which could be accompanied by a visual change. One suggestion would be the following syntax example:
````js
attributes : [{ kind : "airborne", height : 30, variance : 10, movement : "circles" }] // A Pokémon flying around in circles 30px above the ground, in circles of radius 10px
````

**Comment by fuzzball288** [comment]
There is already a floating value in the dex data that's purely visual. http://prntscr.com/63xpxe Also many Pokemon like Beedrill will need floating sprites but won't be able to participate in Sky Battles. We need a field for "can participate in Sky Battles" too but I don't think it needs to be linked to the visual floating effect.

**Comment by varkor** [comment]
Added a slight variation on this scheme in the latest commit. It's separate from Sky Battles though.
