### ISSUE TITLE
Flinch carries over to next turn

### ISSUE THREAD

**Issue by fuzzball288** [varkor/pokengine#177]
Right now if the Pokemon using the flinching move goes second, the next turn the target will flinch. It shouldn't carry over like that. A slower Pokemon can never flinch a target that's already moved.

Also... I did this about 8 times and flinched every time. This is a gif of just two of those. Before the gif: I switched Geomoss in and got hit by Astonish. Turn 1 of the gif, I go first.
http://sta.sh/01awfule70s1

**Comment by varkor** [comment]
Fixed in https://github.com/varkor/pokengine/commit/bea9c79678e2e9d737731868014c4e7e00491a49.
