### ISSUE TITLE
Play music on battle start

### ISSUE THREAD

**Issue by fuzzball288** [varkor/pokengine#188]
We need some tunes!! Should be able to set song by battle type and location. For PvP battles eventually it would be cool to allow the challenger to pick the music for the battle from some list (maybe you can unlock them?) Battle music should override map music.

For now, for Battle Factory, I think we should use a set of songs and have it pick randomly from them each time, but also just playing one song would be better than nothing.

**Comment by varkor** [comment]
I think music is better handled by whatever is initiating the battle (Pokéngine in this case).
