### ISSUE TITLE
Website mismatch to source

### ISSUE THREAD

**Issue by SirProdigle** [varkor/pokengine#207]
Website source code doesn't line up with GitHub source. If downloaded and ran locally, animations and sound won't work.

Trying to fork this to continue work for a personal project but the source seems behind the website. Any chance of updating this or giving me the web source?

**Comment by varkor** [comment]
Some of the settings are disabled on master (simply to make debugging easier). You can enable animations and sounds in `Settings.js`:
https://github.com/varkor/pokengine/blob/b260e6930e238a18f9e455ce80494fbe16b6e221/battle/scripts/objects/unique/Settings.js#L54
https://github.com/varkor/pokengine/blob/b260e6930e238a18f9e455ce80494fbe16b6e221/battle/scripts/objects/unique/Settings.js#L57
